version: '3'

services:
  kafka:
    container_name: kafka-single-broker
    image: 'bitnami/kafka:latest'
    command: >
      sh -c "
        /opt/bitnami/scripts/kafka/run.sh 
        && chmod +x $TEST_HOME/*.sh
        "
    ports:
      - '9094:9094'
    networks:
      - kafka-networks
    volumes:
      - kafka-volumes-0:/bitnami
      - ./scripts:/opt/bitnami/kafka/bin/scripts
    environment:
      # 테스트를 위한 환경변수 설정
      - TEST_HOME=/opt/bitnami/kafka/bin/scripts
      # Kafka 클러스터의 노드 ID를 설정
      # 각 브로커를 고유하게 식별하기 위해 사용 노드 ID는 클러스터 내에서 고유해야 하며, 순차적일 필요는 없지만 일반적으로 관례적으로 0부터 시작하는 정수로 설정
      - KAFKA_CFG_NODE_ID=0
      # 이 노드가 어떤 역할을 수행할 것인지 정의
      # controller: Kafka 클러스터의 컨트롤러 역할을 수행, 클러스터 내의 다른 브로커들을 관리
      # broker: Kafka 클라이언트(프로듀서, 컨슈머)와 메시지를 주고받는 브로커 역할을 수행
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # 클러스터 내의 다른 브로커들과 통신할 수 있는 호스트 및 포트를 설정
      # PLAINTEXT://:9092: 클라이언트와의 통신을 위한 기본 브로커 포트(9092)를 PLAINTEXT(암호화되지 않은)로 설정
      # CONTROLLER://:9093: 컨트롤러 간의 통신을 위한 포트(9093)를 설정
      # EXTERNAL://:9094: 클러스터 외부에서 브로커와 통신하기 위한 포트(9094)를 설정
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # 클러스터 외부에서 브로커와 통신하기 위한 호스트 및 포트를 설정
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      # 클라이언트와의 통신을 위한 보안 프로토콜을 설정
      # PLAINTEXT:PLAINTEXT: 클라이언트와의 통신도 PLAINTEXT 프로토콜 사용
      # CONTROLLER:PLAINTEXT: 컨트롤러 리스너는 PLAINTEXT 프로토콜 사용
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 컨트롤러의 선출을 위한 투표자 목록을 정의
      # 0@kafka:9093: 노드 ID가 0인 브로커(kafka)의 컨트롤러 리스너(9093)를 투표자로 설정
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # 컨트롤러 리스너의 이름을 설정
      # CONTROLLER: 컨트롤러 리스너의 이름을 CONTROLLER로 설정 
      # KAFKA_CFG_LISTENERS에 정의한 리스너 이름 중 하나와 일치해야 함
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 토픽 자동 생성 활성화
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

networks:
  kafka-networks:
    driver: bridge

volumes:
  kafka-volumes-0:
    driver: local
